"""Add admin_message column to apple_passes_data

Revision ID: 0535d2db4946
Revises: 418ae9eb93cd
Create Date: 2026-04-15 10:46:43.680084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0535d2db4946'
down_revision: Union[str, Sequence[str], None] = '418ae9eb93cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Apple_Passes_Data', sa.Column('admin_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apple_Passes_Data', 'admin_message')
    # ### end Alembic commands ###
