"""Refactor Apple Wallet schema to relational structure

Revision ID: 0f7c6c9078f7
Revises: 18cbc9df7200
Create Date: 2026-04-02 12:16:45.500590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f7c6c9078f7'
down_revision: Union[str, Sequence[str], None] = '18cbc9df7200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Pass_Templates',
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('pass_style', sa.String(length=50), nullable=False),
    sa.Column('pass_type_identifier', sa.String(length=255), nullable=False),
    sa.Column('team_identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('Apple_Passes_Data',
    sa.Column('pass_id', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=False),
    sa.Column('holder_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Expired', name='apple_pass_status'), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('foreground_color', sa.String(length=50), nullable=True),
    sa.Column('label_color', sa.String(length=50), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('logo_text', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('strip_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['Apple_Pass_Templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pass_id')
    )
    op.create_index(op.f('ix_Apple_Passes_Data_template_id'), 'Apple_Passes_Data', ['template_id'], unique=False)
    op.create_table('Apple_Pass_Fields',
    sa.Column('field_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pass_id', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('header', 'primary', 'secondary', 'auxiliary', 'back', name='apple_field_type'), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['Apple_Passes_Data.pass_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index(op.f('ix_Apple_Pass_Fields_pass_id'), 'Apple_Pass_Fields', ['pass_id'], unique=False)
    # op.drop_index(op.f('ix_Apple_Passes_Table_class_id'), table_name='Apple_Passes_Table')
    op.drop_table('Apple_Pass_Data')
    op.drop_table('Apple_Passes_Table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Pass_Data',
    sa.Column('serial_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('background_color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('logo_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('icon_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('strip_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('organization_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('logo_text', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('header_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('primary_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('secondary_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('auxiliary_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('back_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['Apple_Passes_Table.serial_number'], name=op.f('1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_number'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Apple_Passes_Table',
    sa.Column('serial_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pass_type_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('holder_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('holder_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('Active', 'Expired'), nullable=False),
    sa.Column('auth_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pass_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('class_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('serial_number'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Apple_Passes_Table_class_id'), 'Apple_Passes_Table', ['class_id'], unique=False)
    op.drop_index(op.f('ix_Apple_Pass_Fields_pass_id'), table_name='Apple_Pass_Fields')
    op.drop_table('Apple_Pass_Fields')
    op.drop_index(op.f('ix_Apple_Passes_Data_template_id'), table_name='Apple_Passes_Data')
    op.drop_table('Apple_Passes_Data')
    op.drop_table('Apple_Pass_Templates')
    # ### end Alembic commands ###
