"""Add Apple_Template_Fields table

Revision ID: 1534dbf65e11
Revises: cd974f2e0977
Create Date: 2026-04-28 10:07:08.510953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1534dbf65e11'
down_revision: Union[str, Sequence[str], None] = 'cd974f2e0977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Template_Fields',
    sa.Column('field_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('header', 'primary', 'secondary', 'auxiliary', 'back', name='apple_field_type'), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['Apple_Pass_Templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index(op.f('ix_Apple_Template_Fields_template_id'), 'Apple_Template_Fields', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Apple_Template_Fields_template_id'), table_name='Apple_Template_Fields')
    op.drop_table('Apple_Template_Fields')
    # ### end Alembic commands ###
