"""create_apple_pass_data_table

Revision ID: 18cbc9df7200
Revises: 39ad04d72133
Create Date: 2026-03-30 11:05:57.798757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cbc9df7200'
down_revision: Union[str, Sequence[str], None] = '39ad04d72133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Pass_Data',
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('strip_url', sa.String(length=512), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('logo_text', sa.String(length=255), nullable=True),
    sa.Column('header_fields', sa.JSON(), nullable=True),
    sa.Column('primary_fields', sa.JSON(), nullable=True),
    sa.Column('secondary_fields', sa.JSON(), nullable=True),
    sa.Column('auxiliary_fields', sa.JSON(), nullable=True),
    sa.Column('back_fields', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['Apple_Passes_Table.serial_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Apple_Pass_Data')
    # ### end Alembic commands ###
