"""remove_apple_classes_table_update_apple_passes

Revision ID: 39ad04d72133
Revises: d7b0b6b636e3
Create Date: 2026-03-30 10:44:43.848017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39ad04d72133'
down_revision: Union[str, Sequence[str], None] = 'd7b0b6b636e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    op.drop_table('Apple_Classes_Table')
    op.add_column('Apple_Passes_Table', sa.Column('class_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Apple_Passes_Table_class_id'), 'Apple_Passes_Table', ['class_id'], unique=False)
    op.drop_constraint(op.f('1'), 'Apple_Passes_Table', type_='foreignkey')
    op.drop_column('GenericClass_Fields', 'multiple_devices_allowed')
    op.drop_column('GenericClass_Fields', 'enable_smart_tap')
    op.drop_column('GenericClass_Fields', 'view_unlock_requirement')
    op.drop_index(op.f('idx_message_object'), table_name='Pass_Messages')
    op.create_index(op.f('ix_Pass_Messages_object_id'), 'Pass_Messages', ['object_id'], unique=False)
    op.drop_index(op.f('idx_text_module_object'), table_name='Pass_Text_Modules')
    op.create_index(op.f('ix_Pass_Text_Modules_object_id'), 'Pass_Text_Modules', ['object_id'], unique=False)
    op.alter_column('Passes_Table', 'object_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique identifier for the pass object (suffix only)',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'class_id',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference to the pass class',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'holder_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the pass holder',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'holder_email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Email of the pass holder',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'status',
               existing_type=mysql.ENUM('Active', 'Expired'),
               comment=None,
               existing_comment='Current status of the pass',
               existing_nullable=False,
               existing_server_default=sa.text("'Active'"))
    op.alter_column('Passes_Table', 'sync_status',
               existing_type=mysql.ENUM('synced', 'pending', 'failed'),
               comment=None,
               existing_comment='Sync status with Google Wallet',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('Passes_Table', 'last_synced_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='When the pass was last synced to Google Wallet',
               existing_nullable=True)
    op.alter_column('Passes_Table', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('Passes_Table', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_table_comment(
        'Passes_Table',
        existing_comment='Stores individual pass instances',
        schema=None
    )
    op.execute('SET FOREIGN_KEY_CHECKS=1;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    op.create_table_comment(
        'Passes_Table',
        'Stores individual pass instances',
        existing_comment=None,
        schema=None
    )
    op.alter_column('Passes_Table', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='Record last update timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('Passes_Table', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='Record creation timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('Passes_Table', 'last_synced_at',
               existing_type=mysql.TIMESTAMP(),
               comment='When the pass was last synced to Google Wallet',
               existing_nullable=True)
    op.alter_column('Passes_Table', 'sync_status',
               existing_type=mysql.ENUM('synced', 'pending', 'failed'),
               comment='Sync status with Google Wallet',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('Passes_Table', 'status',
               existing_type=mysql.ENUM('Active', 'Expired'),
               comment='Current status of the pass',
               existing_nullable=False,
               existing_server_default=sa.text("'Active'"))
    op.alter_column('Passes_Table', 'holder_email',
               existing_type=mysql.VARCHAR(length=255),
               comment='Email of the pass holder',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'holder_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='Name of the pass holder',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'class_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='Reference to the pass class',
               existing_nullable=False)
    op.alter_column('Passes_Table', 'object_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='Unique identifier for the pass object (suffix only)',
               existing_nullable=False)
    op.drop_index(op.f('ix_Pass_Text_Modules_object_id'), table_name='Pass_Text_Modules')
    op.create_index(op.f('idx_text_module_object'), 'Pass_Text_Modules', ['object_id'], unique=False)
    op.drop_index(op.f('ix_Pass_Messages_object_id'), table_name='Pass_Messages')
    op.create_index(op.f('idx_message_object'), 'Pass_Messages', ['object_id'], unique=False)
    op.add_column('GenericClass_Fields', sa.Column('view_unlock_requirement', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('GenericClass_Fields', sa.Column('enable_smart_tap', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('GenericClass_Fields', sa.Column('multiple_devices_allowed', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(op.f('1'), 'Apple_Passes_Table', 'Apple_Classes_Table', ['pass_type_id'], ['pass_type_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Apple_Passes_Table_class_id'), table_name='Apple_Passes_Table')
    op.drop_column('Apple_Passes_Table', 'class_id')
    op.create_table('Apple_Classes_Table',
    sa.Column('pass_type_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('team_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('pass_style', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('organization_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('background_color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('foreground_color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('label_color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('icon_url', mysql.TEXT(), nullable=True),
    sa.Column('logo_url', mysql.TEXT(), nullable=True),
    sa.Column('strip_url', mysql.TEXT(), nullable=True),
    sa.Column('template_json', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('pass_type_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.execute('SET FOREIGN_KEY_CHECKS=1;')
    # ### end Alembic commands ###
