"""Fix Apple Device Registrations Table

Revision ID: 418ae9eb93cd
Revises: e41cee56f419
Create Date: 2026-04-14 14:47:12.157666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '418ae9eb93cd'
down_revision: Union[str, Sequence[str], None] = 'e41cee56f419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Device_Registerations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_library_id', sa.String(length=255), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('pass_type_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_library_id', 'serial_number', name='unique_device_pass')
    )
    op.create_index(op.f('ix_Apple_Device_Registerations_device_library_id'), 'Apple_Device_Registerations', ['device_library_id'], unique=False)
    op.create_index(op.f('ix_Apple_Device_Registerations_serial_number'), 'Apple_Device_Registerations', ['serial_number'], unique=False)
    op.drop_index(op.f('ix_Apple_Device_Registrations_device_library_id'), table_name='Apple_Device_Registrations')
    op.drop_index(op.f('ix_Apple_Device_Registrations_serial_number'), table_name='Apple_Device_Registrations')
    op.drop_index(op.f('unique_device_pass'), table_name='Apple_Device_Registrations')
    op.drop_table('Apple_Device_Registrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Device_Registrations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('device_library_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('push_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('serial_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pass_type_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_device_pass'), 'Apple_Device_Registrations', ['device_library_id', 'serial_number'], unique=True)
    op.create_index(op.f('ix_Apple_Device_Registrations_serial_number'), 'Apple_Device_Registrations', ['serial_number'], unique=False)
    op.create_index(op.f('ix_Apple_Device_Registrations_device_library_id'), 'Apple_Device_Registrations', ['device_library_id'], unique=False)
    op.drop_index(op.f('ix_Apple_Device_Registerations_serial_number'), table_name='Apple_Device_Registerations')
    op.drop_index(op.f('ix_Apple_Device_Registerations_device_library_id'), table_name='Apple_Device_Registerations')
    op.drop_table('Apple_Device_Registerations')
    # ### end Alembic commands ###
