"""Add Apple Wallet tables

Revision ID: 8b4b16c627fe
Revises: 
Create Date: 2026-03-09 14:59:13.960156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b4b16c627fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Classes_Table',
    sa.Column('pass_type_id', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('pass_style', sa.String(length=50), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('foreground_color', sa.String(length=50), nullable=True),
    sa.Column('label_color', sa.String(length=50), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('strip_url', sa.Text(), nullable=True),
    sa.Column('template_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pass_type_id')
    )
    op.create_table('Apple_Device_Registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_library_id', sa.String(length=255), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('pass_type_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_library_id', 'serial_number', name='unique_device_pass')
    )
    op.create_index(op.f('ix_Apple_Device_Registrations_device_library_id'), 'Apple_Device_Registrations', ['device_library_id'], unique=False)
    op.create_index(op.f('ix_Apple_Device_Registrations_serial_number'), 'Apple_Device_Registrations', ['serial_number'], unique=False)
    op.create_table('Apple_Notifications_Table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pass_type_id', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Sent', 'Failed', name='apple_notif_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Apple_Notifications_Table_created_at'), 'Apple_Notifications_Table', ['created_at'], unique=False)
    op.create_index(op.f('ix_Apple_Notifications_Table_pass_type_id'), 'Apple_Notifications_Table', ['pass_type_id'], unique=False)
    op.create_index(op.f('ix_Apple_Notifications_Table_serial_number'), 'Apple_Notifications_Table', ['serial_number'], unique=False)
    op.create_table('Apple_Passes_Table',
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('pass_type_id', sa.String(length=255), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=False),
    sa.Column('holder_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Expired', name='apple_pass_status'), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=False),
    sa.Column('pass_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pass_type_id'], ['Apple_Classes_Table.pass_type_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Apple_Passes_Table')
    op.drop_index(op.f('ix_Apple_Notifications_Table_serial_number'), table_name='Apple_Notifications_Table')
    op.drop_index(op.f('ix_Apple_Notifications_Table_pass_type_id'), table_name='Apple_Notifications_Table')
    op.drop_index(op.f('ix_Apple_Notifications_Table_created_at'), table_name='Apple_Notifications_Table')
    op.drop_table('Apple_Notifications_Table')
    op.drop_index(op.f('ix_Apple_Device_Registrations_serial_number'), table_name='Apple_Device_Registrations')
    op.drop_index(op.f('ix_Apple_Device_Registrations_device_library_id'), table_name='Apple_Device_Registrations')
    op.drop_table('Apple_Device_Registrations')
    op.drop_table('Apple_Classes_Table')
    # ### end Alembic commands ###
