"""add_module_type_columns

Revision ID: cd974f2e0977
Revises: 0535d2db4946
Create Date: 2026-04-21 09:42:36.337958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd974f2e0977'
down_revision: Union[str, Sequence[str], None] = '0535d2db4946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GenericClass_TextModuleRows', sa.Column('left_type', sa.String(length=50), server_default='text', nullable=False))
    op.add_column('GenericClass_TextModuleRows', sa.Column('middle_type', sa.String(length=50), server_default='text', nullable=False))
    op.add_column('GenericClass_TextModuleRows', sa.Column('right_type', sa.String(length=50), server_default='text', nullable=False))
    op.add_column('Pass_Text_Modules', sa.Column('module_type', sa.String(length=50), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pass_Text_Modules', 'module_type')
    op.drop_column('GenericClass_TextModuleRows', 'right_type')
    op.drop_column('GenericClass_TextModuleRows', 'middle_type')
    op.drop_column('GenericClass_TextModuleRows', 'left_type')
    # ### end Alembic commands ###
