"""add_apple_event_ticket_layouts

Revision ID: e41cee56f419
Revises: 0f7c6c9078f7
Create Date: 2026-04-09 10:23:31.944868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41cee56f419'
down_revision: Union[str, Sequence[str], None] = '0f7c6c9078f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Apple_Passes_Data', sa.Column('background_image_url', sa.String(length=512), nullable=True))
    op.add_column('Apple_Passes_Data', sa.Column('thumbnail_url', sa.String(length=512), nullable=True))
    op.add_column('Apple_Passes_Data', sa.Column('ticket_layout', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apple_Passes_Data', 'ticket_layout')
    op.drop_column('Apple_Passes_Data', 'thumbnail_url')
    op.drop_column('Apple_Passes_Data', 'background_image_url')
    # ### end Alembic commands ###
